<footer>
<ul>
<li><a class="tst-home" href="{{{base}}}/index.html">Home</a></li>
<li><a class="tst-sensor-types-search" href="{{{base}}}/sensor-types.html">Search Sensor Types</a></li>
<li><a class="tst-sensor-types-add" href="{{{base}}}/sensor-types/add.html">Add Sensor Types</a></li>
<li><a class="tst-sensors-search" href="{{{base}}}/sensors.html">Search Sensor</a></li>
<li><a class="tst-sensors-add" href="{{{base}}}/sensors/add.html">Add Sensor</a></li>
</ul>
</footer>