<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search Sensor Types</title>
    <link rel="stylesheet" href="/css/style.css">
</head>
<body>
    <div class="page">
        <h1 class="tst-sensor-types-search-page">Search Sensor Types</h1>
        <form method="GET"> 
        {{#form}}
            {{{render}}}
         {{/form}}
        </form>
    {{>footer}}
</body>
</html>