<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Source file</title>
<style type="text/css">
/* highlight theme: Emacs Editor */
body.hl	{ background-color:#ffffff; }
pre.hl	{ color:#000000; background-color:#ffffff; font-size:10pt; font-family:'Courier New',monospace;}
.hl.num { color:#000000; }
.hl.esc { color:#ff00ff; }
.hl.str { color:#bd8d8b; }
.hl.pps { color:#bd8d8b; }
.hl.slc { color:#ac2020; font-style:italic; }
.hl.com { color:#ac2020; font-style:italic; }
.hl.ppc { color:#000000; }
.hl.opt { color:#000000; }
.hl.ipl { color:#ff00ff; }
.hl.lin { color:#555555; }
.hl.kwa { color:#9c20ee; font-weight:bold; }
.hl.kwb { color:#208920; }
.hl.kwc { color:#0000ff; }
.hl.kwd { color:#000000; }
</style>
</head>
<body class="hl">
<pre class="hl"><span class="hl kwa">const</span> cors <span class="hl opt">=</span> <span class="hl kwd">require</span><span class="hl opt">(</span><span class="hl str">&apos;cors&apos;</span><span class="hl opt">);</span>
<span class="hl kwa">const</span> express <span class="hl opt">=</span> <span class="hl kwd">require</span><span class="hl opt">(</span><span class="hl str">&apos;express&apos;</span><span class="hl opt">);</span>
<span class="hl kwa">const</span> bodyParser <span class="hl opt">=</span> <span class="hl kwd">require</span><span class="hl opt">(</span><span class="hl str">&apos;body-parser&apos;</span><span class="hl opt">);</span>

<span class="hl kwa">const</span> AppError <span class="hl opt">=</span> <span class="hl kwd">require</span><span class="hl opt">(</span><span class="hl str">&apos;./app-error&apos;</span><span class="hl opt">);</span>

<span class="hl kwa">const</span> OK <span class="hl opt">=</span> <span class="hl num">200</span><span class="hl opt">;</span>
<span class="hl kwa">const</span> CREATED <span class="hl opt">=</span> <span class="hl num">201</span><span class="hl opt">;</span>
<span class="hl kwa">const</span> BAD_REQUEST <span class="hl opt">=</span> <span class="hl num">400</span><span class="hl opt">;</span>
<span class="hl kwa">const</span> NOT_FOUND <span class="hl opt">=</span> <span class="hl num">404</span><span class="hl opt">;</span>
<span class="hl kwa">const</span> CONFLICT <span class="hl opt">=</span> <span class="hl num">409</span><span class="hl opt">;</span>
<span class="hl kwa">const</span> SERVER_ERROR <span class="hl opt">=</span> <span class="hl num">500</span><span class="hl opt">;</span>

<span class="hl kwa">function</span> <span class="hl kwd">serve</span><span class="hl opt">(</span>port<span class="hl opt">,</span> sensors<span class="hl opt">) {</span>
  <span class="hl slc">//&#64;TODO set up express app, routing and listen</span>
<span class="hl opt">}</span>

module<span class="hl opt">.</span>exports <span class="hl opt">= {</span> serve <span class="hl opt">};</span>

<span class="hl slc">//&#64;TODO routing function, handlers, utility functions</span>
</pre>
</body>
</html>
<!--HTML generated by highlight 3.41, http://www.andre-simon.de/-->
